development:
  host: localhost
  database: lypc

test:
  host: localhost
  database: lypc_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  #host: localhost
  #database: mongocms
  #uri: "mongodb://heroku:a100c51a1aeddacc08174d4c7facfe1c@staff.mongohq.com:10027/app2392207"
