development:
  host: localhost
  database: mongo_cms

test:
  host: localhost
  database: mongo_cms_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  #host: localhost
  #database: mongo_cms
